version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8000"
    depends_on:
      - db
    networks:
      - laravel_net

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  postgres_data: